name = "NGSCheckMate"
uuid = "8c8e3a20-7c8d-4b5a-9c8d-1e2f3a4b5c6d"
authors = ["nagendraKU"]
version = "1.0.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
GeneticVariation = "9bc6ac9d-e6b2-5f70-b0a8-242a01662520"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
ArgParse = "1"
Clustering = "0.15"
GeneticVariation = "0.4, 0.5"
StatsPlots = "0.15"
julia = "1.6"
